### ISSUE TITLE
Support removing a relationship

### ISSUE THREAD

**Issue by walkerrandolphsmith** [versionone/VersionOne.SDK.JavaScript#31]
Currently only adding relations is supported by passing an array of oid tokens. We also need to support removing relations. Possible solution would be to pass an array of tuples (oid token, intention) for each relation. https://github.com/versionone/VersionOne.SDK.JavaScript/blob/master/src/transformDataToAsset.js Possible solution looks something like:  

```
[
    { "idref": "Story:123", "act": "add" },
    { "idref": "Story:456", "act": "remove" }
]
```

**Comment by JogoShugh** [comment]
I like that...

Another thought:

```javascript
{
  add: ["Story:123", "Story:125"],
  remove: ["Story:456", "Story:898"]
}
```

**Comment by walkerrandolphsmith** [comment]
Sorry come to find out if you pass it an array of strings it assumes adding a relation, but if you need to remove a relation you can pass it `{ "idref": "Story:123", "act": "remove" }`

**Comment by JogoShugh** [comment]
Hmm, i wasn't suggesting passing that, but translating to the more verbose syntax just in time before the Post

**Comment by walkerrandolphsmith** [comment]
@JogoShugh, yeah passing two arrays was considered. I didn't realize the sdk already supported removing and adding relations so I closed the issue.
