### ISSUE TITLE
Need user-facing message when token is not valid

### ISSUE THREAD

**Issue by aclairefication** [versionone/VersionOne.SDK.JavaScript#36]
When trying to authenticate with a token, clicking on the Submit button did not produce a visible result.

Although there is no user-facing messaging, the browser console contains this message:
Failed to load resource: the server responded with a status of 401 (Unauthorized)

**Comment by walkerrandolphsmith** [comment]
@aclairefication I believe this is a Planr issues as the SDK does not have a user interface. I will close this issue and move it to the appropriate project.
